yamlfile:
    test: this is test for yaml file

---
spring:
    profiles: profile

yamlfile:
   test: this is a test for yaml file for another properity

---
solr:
    host: "http://192.168.82.165:8983/solr"